// Blog-System für SEO Long-Tail-Traffic
// Stand: Mai 2026

export interface BlogPost {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  excerpt: string;
  publishedAt: string; // ISO date
  updatedAt: string;
  readingTimeMin: number;
  category: string;
  keywords: string[];
  // Strukturierte Inhalte: Mischung aus Absätzen, Headings, Listen
  content: BlogBlock[];
}

export type BlogBlock =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "ol"; items: string[] }
  | { type: "quote"; text: string }
  | { type: "links"; title: string; items: { label: string; to: string }[] };

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "was-kostet-entruempelung-falkensee-2026",
    title: "Was kostet eine Entrümpelung in Falkensee 2026? Preise, Beispiele & Spartipps",
    metaTitle: "Was kostet eine Entrümpelung in Falkensee? | Preise 2026",
    metaDescription:
      "Ehrliche Preisübersicht für Entrümpelungen in Falkensee 2026: Wohnung, Haus, Keller. Mit Rechenbeispielen, Spartipps und Festpreisgarantie. ☎ 01579 2639408",
    excerpt:
      "Wie viel kostet eine Entrümpelung in Falkensee wirklich? Wir zeigen transparente Festpreise nach Volumen, drei reale Beispielrechnungen und vier Spartipps, mit denen Sie hunderte Euro sparen.",
    publishedAt: "2026-05-14",
    updatedAt: "2026-05-14",
    readingTimeMin: 6,
    category: "Preise & Ratgeber",
    keywords: [
      "entrümpelung falkensee preise",
      "kosten entrümpelung falkensee",
      "wohnungsauflösung falkensee",
      "haushaltsauflösung kosten havelland",
    ],
    content: [
      {
        type: "p",
        text: "Eine Entrümpelung in Falkensee kostet im Schnitt zwischen 299 € (kleiner Keller) und 4.500 € (großes Einfamilienhaus). Der Endpreis hängt vor allem vom Volumen, vom Zugang zur Immobilie und davon ab, ob Sondermüll anfällt. In diesem Ratgeber zeigen wir Ihnen ehrliche Preisspannen für 2026, drei reale Beispiele aus Falkensee und wie Sie bares Geld sparen.",
      },
      { type: "h2", text: "Preisübersicht: Entrümpelung Falkensee 2026" },
      {
        type: "p",
        text: "Als Direktanbieter aus dem benachbarten Brieselang arbeiten wir in Falkensee mit transparenten Festpreisen nach Volumen. Es gibt keine Anfahrtskosten und die Besichtigung ist kostenlos. Folgende Richtwerte gelten 2026:",
      },
      {
        type: "ul",
        items: [
          "Kellerentrümpelung (klein, bis 10 m³): ab 299 €",
          "1-Zimmer-Wohnung (bis 25 m³): ab 690 €",
          "2-Zimmer-Wohnung (bis 40 m³): ab 1.190 €",
          "3-4-Zimmer-Wohnung (bis 60 m³): ab 1.690 €",
          "Einfamilienhaus inkl. Keller & Dachboden: ab 2.490 €",
          "Großes Haus mit Garage / Nebengebäuden: 3.500 – 4.500 €",
        ],
      },
      {
        type: "p",
        text: "Wichtig: Diese Preise sind Festpreise nach Besichtigung – keine versteckten Aufschläge, keine Stundenabrechnung, keine Anfahrtskosten innerhalb von Falkensee und Umgebung.",
      },
      { type: "h2", text: "Drei reale Beispiele aus Falkensee" },
      { type: "h3", text: "Beispiel 1: 2-Zimmer-Wohnung in Falkenhöh" },
      {
        type: "p",
        text: "Eine ältere Dame zog ins Pflegeheim, die Wohnung in Falkenhöh musste komplett geräumt werden – inklusive Keller. Insgesamt rund 35 m³ Hausrat, normale Möbel, kein Sondermüll. Festpreis: 1.290 € inklusive besenreiner Übergabe an den Vermieter.",
      },
      { type: "h3", text: "Beispiel 2: Einfamilienhaus in Finkenkrug nach Erbfall" },
      {
        type: "p",
        text: "Nach einem Todesfall musste ein Haus aus den 1970er-Jahren komplett aufgelöst werden: 2 Etagen, Keller, Dachboden, Garage. Sentimentale Gegenstände wurden vorsortiert übergeben, der Rest entsorgt. Festpreis: 3.190 € – inklusive Sperrmüll, Elektrogeräten und besenreiner Übergabe.",
      },
      { type: "h3", text: "Beispiel 3: Kellerentrümpelung in Seegefeld" },
      {
        type: "p",
        text: "Ein Mieter wollte vor dem Auszug seinen Kellerraum räumen lassen: alte Möbel, Kartons, Werkstattreste. Volumen: 8 m³. Festpreis: 349 €. Ausgeführt am Tag nach der Besichtigung.",
      },
      { type: "h2", text: "Was beeinflusst den Preis?" },
      {
        type: "ul",
        items: [
          "Volumen in m³ (wichtigster Faktor)",
          "Zugang: Erdgeschoss vs. 4. Stock ohne Aufzug",
          "Sondermüll: Asbest, Farben, Chemikalien (selten)",
          "Wertanrechnung: Verwertbares senkt den Preis",
          "Termindruck: Express-Räumungen kosten mehr",
        ],
      },
      { type: "h2", text: "4 Spartipps für Ihre Entrümpelung in Falkensee" },
      {
        type: "ol",
        items: [
          "Vorsortieren: Was Sie selbst behalten oder verschenken, muss nicht entsorgt werden – jedes m³ weniger spart bares Geld.",
          "Wertanrechnung nutzen: Antiquitäten, Kupfer, Messing oder gut erhaltene Möbel können wir anrechnen und vom Preis abziehen.",
          "Festpreis statt Stundenlohn: Lassen Sie sich nie nach Stunden abrechnen – nur ein verbindlicher Festpreis schützt vor bösen Überraschungen.",
          "Direktanbieter wählen: Vermittlungsplattformen verlangen 15–25 % Aufschlag. Wir arbeiten mit eigenem Team aus Brieselang – ohne Mittelsmann.",
        ],
      },
      { type: "h2", text: "Wie läuft eine Entrümpelung in Falkensee ab?" },
      {
        type: "ol",
        items: [
          "Anruf oder WhatsApp – wir vereinbaren einen Termin innerhalb von 24–48 Stunden.",
          "Kostenlose Besichtigung vor Ort in Falkensee – unverbindlich.",
          "Verbindliches Festpreisangebot, schriftlich.",
          "Räumung durch unser eigenes Team mit eigenen Fahrzeugen.",
          "Besenreine Übergabe und fachgerechte Entsorgung.",
        ],
      },
      {
        type: "quote",
        text: "Festpreis statt Stundenlohn – das ist für uns Standard. Unsere Kunden sollen vorher wissen, was sie bezahlen. Kein Risiko, keine Nachforderungen.",
      },
      { type: "h2", text: "Häufige Fragen" },
      { type: "h3", text: "Berechnen Sie Anfahrtskosten in Falkensee?" },
      {
        type: "p",
        text: "Nein. Falkensee liegt direkt neben unserem Standort Brieselang – Anfahrt und Besichtigung sind 100 % kostenlos.",
      },
      { type: "h3", text: "Wie schnell sind Sie vor Ort?" },
      {
        type: "p",
        text: "In der Regel innerhalb von 24–48 Stunden zur Besichtigung. Express-Termine am selben Tag sind möglich.",
      },
      { type: "h3", text: "Übernehmen Sie auch die Entsorgung?" },
      {
        type: "p",
        text: "Ja, alles aus einer Hand: Räumung, Transport, Trennung und fachgerechte Entsorgung gemäß Kreislaufwirtschaftsgesetz – inklusive Entsorgungsnachweis auf Wunsch.",
      },
      { type: "h2", text: "Jetzt kostenloses Festpreisangebot für Falkensee anfordern" },
      {
        type: "p",
        text: "Rufen Sie uns an unter 01579 2639408 oder schreiben Sie uns per WhatsApp. Sie bekommen innerhalb von 24 Stunden einen Besichtigungstermin und kurz darauf Ihren verbindlichen Festpreis. Persönlich, lokal, ehrlich – seit 2015 im Havelland.",
      },
    ],
  },
  {
    slug: "was-kostet-eine-entruempelung-preise-2026",
    title: "Was kostet eine Entrümpelung 2026? Preise, Rechenbeispiele & Spartipps",
    metaTitle: "Was kostet eine Entrümpelung 2026? | Preise pro m³ & qm",
    metaDescription:
      "Aktuelle Preise für Entrümpelung 2026: Wohnung, Haus, Keller. Realistische Kosten pro m³ und m², 5 Rechenbeispiele und Spartipps. ☎ 01579 2639408",
    excerpt:
      "Eine Entrümpelung kostet 2026 im Schnitt 35–80 € pro m³ – je nach Volumen, Zugang und Sondermüll. Wir zeigen ehrliche Preisspannen, fünf Rechenbeispiele aus dem Havelland und vier konkrete Spartipps.",
    publishedAt: "2026-05-07",
    updatedAt: "2026-05-18",
    readingTimeMin: 8,
    category: "Preise & Ratgeber",
    keywords: [
      "entrümpelung kosten",
      "was kostet eine entrümpelung",
      "entrümpelung kosten pro qm",
      "entrümpelung preise",
      "haushaltsauflösung kosten",
    ],
    content: [
      {
        type: "p",
        text: "Eine Entrümpelung kostet in Deutschland 2026 im Schnitt zwischen 35 € und 80 € pro Kubikmeter – je nach Volumen, Etage, Zugang und ob Sondermüll anfällt. Für eine 2-Zimmer-Wohnung sollten Sie 1.000 bis 1.800 € einplanen, für ein komplettes Einfamilienhaus 2.500 bis 4.500 €. In diesem Ratgeber finden Sie ehrliche Preisspannen, fünf Rechenbeispiele und die wichtigsten Spartipps.",
      },
      { type: "h2", text: "Preisübersicht 2026: Was kostet eine Entrümpelung?" },
      {
        type: "p",
        text: "Die meisten seriösen Entrümpelungsfirmen arbeiten heute mit Festpreisen nach Volumen (m³) – nicht nach Stunden. Das schützt Sie vor Nachforderungen. Folgende Richtwerte gelten 2026 im Havelland und Berliner Umland:",
      },
      {
        type: "ul",
        items: [
          "Kellerentrümpelung (bis 10 m³): 299 – 690 €",
          "Dachbodenentrümpelung (bis 15 m³): 399 – 890 €",
          "1-Zimmer-Wohnung (bis 25 m³): 690 – 1.190 €",
          "2-Zimmer-Wohnung (bis 40 m³): 1.190 – 1.890 €",
          "3-4-Zimmer-Wohnung (bis 60 m³): 1.690 – 2.690 €",
          "Einfamilienhaus komplett: 2.490 – 4.500 €",
          "Messie-Wohnung (mit Aufschlag): +30 – 60 %",
        ],
      },
      { type: "h2", text: "Entrümpelung Kosten pro m² und pro m³" },
      {
        type: "p",
        text: "Viele Anbieter rechnen pro Kubikmeter – das ist die fairste Methode, weil leere Hochregale weniger kosten als vollgestopfte Räume. Als Faustregel gilt: 1 m² Wohnfläche entspricht ca. 0,3 bis 0,5 m³ Hausrat. Pro m² Wohnfläche kommen Sie damit auf rund 15 – 35 € Entrümpelungskosten.",
      },
      {
        type: "ul",
        items: [
          "Normal möbliert: ca. 35 – 55 € pro m³",
          "Vollgestopft / Messie: 60 – 80 € pro m³",
          "Schwerer Zugang (Altbau, kein Aufzug): +10 – 20 %",
          "Sondermüll (Asbest, Farben, Öl): nach Aufwand",
        ],
      },
      { type: "h2", text: "5 Rechenbeispiele aus dem Havelland" },
      { type: "h3", text: "Beispiel 1: Keller in Brieselang (8 m³)" },
      { type: "p", text: "Mieter wollte vor dem Auszug seinen Keller räumen lassen – Werkstattreste, alte Möbel, Kartons. Festpreis: 349 €." },
      { type: "h3", text: "Beispiel 2: 2-Zimmer-Wohnung in Falkensee (35 m³)" },
      { type: "p", text: "Wohnungsauflösung nach Umzug ins Pflegeheim, kein Sondermüll, Erdgeschoss. Festpreis: 1.290 € inklusive besenreiner Übergabe." },
      { type: "h3", text: "Beispiel 3: Einfamilienhaus in Nauen (90 m³)" },
      { type: "p", text: "Haushaltsauflösung nach Erbfall, 2 Etagen, Keller, Dachboden, Garage. Festpreis: 3.190 €." },
      { type: "h3", text: "Beispiel 4: Dachboden in Oranienburg (12 m³)" },
      { type: "p", text: "Sperrgut, Kartons, alte Elektrogeräte. Enger Zugang über Bodentreppe. Festpreis: 590 €." },
      { type: "h3", text: "Beispiel 5: Gewerberäume in Hennigsdorf (50 m³)" },
      { type: "p", text: "Bürodemontage, Aktenvernichtung, Sperrmüll. Festpreis: 1.890 € inklusive DSGVO-konformer Entsorgung." },
      {
        type: "links",
        title: "Festpreise pro Leistung",
        items: [
          { label: "Wohnungsentrümpelung", to: "/wohnungsentruempelung" },
          { label: "Hausentrümpelung", to: "/hausentruempelung" },
          { label: "Kellerentrümpelung", to: "/kellerentruempelung" },
          { label: "Dachbodenentrümpelung", to: "/dachbodenentruempelung" },
          { label: "Haushaltsauflösung", to: "/haushaltsaufloesung" },
          { label: "Alle Preise im Überblick", to: "/preise" },
        ],
      },
      { type: "h2", text: "Was beeinflusst den Preis konkret?" },
      {
        type: "ul",
        items: [
          "Volumen in m³ – der wichtigste Faktor",
          "Etage und Zugang (Aufzug, Treppenbreite)",
          "Verwertbares (Antiquitäten, Metall) reduziert den Preis",
          "Sondermüll, Asbest, Mineralwolle erhöhen ihn",
          "Termindruck: Express-Räumungen kosten 10–20 % mehr",
        ],
      },
      { type: "h2", text: "4 Spartipps für 2026" },
      {
        type: "ol",
        items: [
          "Vorsortieren: Was Sie behalten oder verschenken, muss nicht entsorgt werden – jeder m³ weniger spart 35–80 €.",
          "Wertanrechnung nutzen: Kupfer, Messing, Antiquitäten und gut erhaltene Möbel werden angerechnet. Mehr dazu in unserem Ratgeber 'Entrümpelung mit Wertanrechnung'.",
          "Direktanbieter wählen: Vermittlungsplattformen verlangen 15–25 % Aufschlag. Wir arbeiten mit eigenem Team aus Brieselang – ohne Mittelsmann.",
          "Festpreis schriftlich: Lassen Sie sich nie nach Stunden abrechnen – nur ein verbindlicher Festpreis schützt vor Nachforderungen.",
        ],
      },
      {
        type: "links",
        title: "Wir entrümpeln in Ihrer Region",
        items: [
          { label: "Brieselang", to: "/entruempelung-brieselang" },
          { label: "Falkensee", to: "/entruempelung-falkensee" },
          { label: "Nauen", to: "/entruempelung-nauen" },
          { label: "Oranienburg", to: "/entruempelung-oranienburg" },
          { label: "Hennigsdorf", to: "/entruempelung-hennigsdorf" },
          { label: "Rathenow", to: "/entruempelung-rathenow" },
          { label: "Havelland (Übersicht)", to: "/entruempelung-havelland" },
        ],
      },
      { type: "h2", text: "Häufige Fragen zu den Kosten" },
      { type: "h3", text: "Was kostet eine Entrümpelung pro qm?" },
      { type: "p", text: "Pro Quadratmeter Wohnfläche zahlen Sie 2026 ca. 15–35 €. Bei stark vollgestopften Wohnungen kann es auch 40–60 €/m² werden." },
      { type: "h3", text: "Wer zahlt die Entrümpelung bei Mietnomaden oder im Erbfall?" },
      { type: "p", text: "Im Erbfall trägt die Erbengemeinschaft die Kosten. Bei Mietnomaden zahlt der Vermieter und kann die Kosten zivilrechtlich vom Mieter zurückfordern. Details dazu in unserem Ratgeber 'Wer trägt die Kosten einer Entrümpelung?'." },
      { type: "h3", text: "Sind Festpreise wirklich verbindlich?" },
      { type: "p", text: "Ja – nach unserer kostenlosen Besichtigung erhalten Sie ein schriftliches Festpreisangebot. Es gibt keine Nachforderungen, auch wenn die Räumung länger dauert." },
      {
        type: "quote",
        text: "Ein ehrlicher Festpreis ist 2026 das wichtigste Kriterium. Wer nach Stunden abrechnet, hat etwas zu verbergen.",
      },
      { type: "h2", text: "Jetzt kostenloses Festpreisangebot anfordern" },
      { type: "p", text: "Rufen Sie an unter 01579 2639408 oder schreiben Sie per WhatsApp. Sie erhalten innerhalb von 24 Stunden einen Besichtigungstermin und kurz darauf Ihren verbindlichen Festpreis – im gesamten Havelland und Berliner Umland." },
    ],
  },
  {
    slug: "entruempelung-mit-wertanrechnung",
    title: "Entrümpelung mit Wertanrechnung: So reduzieren Sie den Preis 2026",
    metaTitle: "Entrümpelung mit Wertanrechnung | Preis senken 2026",
    metaDescription:
      "Wie Sie mit Wertanrechnung bei der Entrümpelung 100–800 € sparen: was zählt, wie Anbieter rechnen, worauf Sie achten müssen. Ehrlicher Ratgeber 2026.",
    excerpt:
      "Wertanrechnung kann den Preis einer Entrümpelung um 100–800 € reduzieren – wenn der Anbieter ehrlich rechnet. Wir zeigen, was wirklich Geld bringt, wie Sie sich nicht über den Tisch ziehen lassen, und welche Stücke meistens überschätzt werden.",
    publishedAt: "2026-05-21",
    updatedAt: "2026-05-18",
    readingTimeMin: 6,
    category: "Preise & Ratgeber",
    keywords: [
      "entrümpelung mit wertanrechnung",
      "wertanrechnung haushaltsauflösung",
      "entrümpelung preis reduzieren",
      "ankauf bei entrümpelung",
    ],
    content: [
      {
        type: "p",
        text: "Wertanrechnung bedeutet: Verwertbare Gegenstände werden vom Entrümpelungspreis abgezogen. Realistisch sind Einsparungen von 100–800 € – bei wertvollen Antiquitäten oder größeren Metallmengen auch mehr. In diesem Ratgeber zeigen wir, was 2026 tatsächlich Geld bringt, welche Stücke regelmäßig überschätzt werden und wie Sie sich vor unseriösen 'Schein-Anrechnungen' schützen.",
      },
      { type: "h2", text: "Was bringt bei der Wertanrechnung wirklich Geld?" },
      {
        type: "ul",
        items: [
          "Altmetall (Kupfer, Messing, Aluminium, Edelstahl) – aktuell 0,80 – 6 €/kg",
          "Antiquitäten mit nachweisbarem Marktwert (Möbel vor 1930, Porzellan, Silberbesteck)",
          "Markenwerkzeug und Maschinen (Hilti, Bosch Profi, Festool)",
          "Gut erhaltene Designermöbel (Vitra, Thonet, USM Haller)",
          "Funktionsfähige Elektrogeräte (max. 5 Jahre alt, A++)",
          "Goldschmuck, Münzen, Briefmarken (mit Sachverstand zu prüfen)",
        ],
      },
      { type: "h2", text: "Was wird regelmäßig überschätzt?" },
      {
        type: "ul",
        items: [
          "Eichenschränke, Schrankwände der 70er/80er – meist 0 € Marktwert",
          "Röhrenfernseher, alte PCs, Großbildschirme – Entsorgung kostet eher",
          "Klavier ohne Klangqualität – Transport teurer als Erlös",
          "Geschirr und Bücher in Standardausführung – kein Markt",
          "Polstermöbel mit Gebrauchsspuren – Entsorgungspflicht",
        ],
      },
      { type: "h2", text: "So rechnet ein seriöser Anbieter" },
      { type: "p", text: "Bei der kostenlosen Besichtigung schätzt der Anbieter den Verwertungswert ehrlich ein. Diese Summe wird transparent vom Festpreis abgezogen und steht schriftlich im Angebot. Beispiel: Räumung 1.800 €, Wertanrechnung Kupfer + Antikschrank −350 €, Endpreis 1.450 €." },
      {
        type: "quote",
        text: "Wertanrechnung ist kein Bauchgefühl, sondern eine konkrete Zahl im schriftlichen Angebot. Wer 'irgendwas anrechnet' ohne Betrag, meint es nicht ernst.",
      },
      { type: "h2", text: "5 Tipps für maximale Anrechnung" },
      {
        type: "ol",
        items: [
          "Nichts vorab wegwerfen – auch unscheinbare Stücke können Wert haben.",
          "Holzart, Marke, Herstellungsjahr vorab recherchieren oder im Internet vergleichen.",
          "Metall vorsortieren: Kupferkabel von Eisen trennen erhöht den Erlös deutlich.",
          "Zwei Angebote einholen – die Wertanrechnung kann sich um mehrere hundert Euro unterscheiden.",
          "Anrechnung schriftlich im Angebot festhalten lassen – nie auf mündliche Zusagen vertrauen.",
        ],
      },
      {
        type: "links",
        title: "Passende Leistungen mit Wertanrechnung",
        items: [
          { label: "Haushaltsauflösung", to: "/haushaltsaufloesung" },
          { label: "Wohnungsentrümpelung", to: "/wohnungsentruempelung" },
          { label: "Hausentrümpelung", to: "/hausentruempelung" },
          { label: "Schrottabholung (kostenlos)", to: "/schrottabholung" },
        ],
      },
      { type: "h2", text: "Schrott kostenlos abholen lassen" },
      { type: "p", text: "Bei größeren Mengen Altmetall holen wir Schrott im Havelland sogar kostenlos ab. Das ist keine Wertanrechnung im klassischen Sinn, spart Ihnen aber Entsorgungskosten. Details auf unserer Seite zur Schrottabholung." },
      { type: "h2", text: "Häufige Fragen zur Wertanrechnung" },
      { type: "h3", text: "Wird die Wertanrechnung sofort ausgezahlt?" },
      { type: "p", text: "Nein – sie wird vom Räumungspreis abgezogen. Sie bezahlen also weniger, statt Geld zu erhalten. Nur bei Reinankauf (sehr wertvolle Einzelstücke) gibt es eine separate Auszahlung." },
      { type: "h3", text: "Wer schätzt die Werte ein?" },
      { type: "p", text: "Bei uns macht das ein erfahrener Mitarbeiter direkt vor Ort bei der kostenlosen Besichtigung. Bei besonders wertvollen Stücken ziehen wir auf Wunsch einen Sachverständigen hinzu." },
      { type: "h3", text: "Was passiert, wenn nichts anrechenbar ist?" },
      { type: "p", text: "Dann bleibt es beim regulären Festpreis. Sie zahlen aber nie mehr – nur eventuell weniger." },
      {
        type: "links",
        title: "Wir entrümpeln in Ihrer Region",
        items: [
          { label: "Brieselang", to: "/entruempelung-brieselang" },
          { label: "Falkensee", to: "/entruempelung-falkensee" },
          { label: "Nauen", to: "/entruempelung-nauen" },
          { label: "Oranienburg", to: "/entruempelung-oranienburg" },
          { label: "Hennigsdorf", to: "/entruempelung-hennigsdorf" },
        ],
      },
      { type: "h2", text: "Jetzt ehrliche Wertanrechnung anfragen" },
      { type: "p", text: "Rufen Sie an unter 01579 2639408 – wir kommen kostenlos zur Besichtigung und nennen Ihnen einen ehrlichen Festpreis inklusive Wertanrechnung, schriftlich." },
    ],
  },
  {
    slug: "wer-traegt-kosten-entruempelung",
    title: "Wer trägt die Kosten einer Entrümpelung? Erbfall, Mietnomaden, Pflegefall, Sozialamt",
    metaTitle: "Wer zahlt die Entrümpelung? | Erbe, Vermieter, Sozialamt 2026",
    metaDescription:
      "Wer trägt die Kosten einer Entrümpelung? Klare Antworten für Erbfall, Mietnomaden, Pflegefall, Tod und Sozialamt – mit Rechtsgrundlagen 2026.",
    excerpt:
      "Wer zahlt eine Entrümpelung? Im Erbfall die Erben, bei Mietnomaden zunächst der Vermieter, im Pflegefall meist der Betroffene oder die Familie. Wir klären die wichtigsten Konstellationen mit Paragrafen und Praxis-Tipps.",
    publishedAt: "2026-05-12",
    updatedAt: "2026-05-18",
    readingTimeMin: 7,
    category: "Recht & Ratgeber",
    keywords: [
      "wer trägt die kosten der entrümpelung",
      "wer zahlt entrümpelung erbfall",
      "entrümpelung mietnomaden kosten",
      "entrümpelung sozialamt",
      "entrümpelung sterbefall wer zahlt",
    ],
    content: [
      {
        type: "p",
        text: "Die Kosten einer Entrümpelung trägt grundsätzlich derjenige, dem die Sachen gehören – oder dessen Rechtsnachfolger. Im Erbfall sind das die Erben, bei Mietnomaden zunächst der Vermieter (der die Kosten zurückfordern kann), im Pflegefall der Betroffene oder dessen Angehörige. Wir erklären alle Konstellationen mit den entsprechenden Paragrafen und was Sie 2026 in der Praxis beachten müssen.",
      },
      { type: "h2", text: "1. Entrümpelung im Erbfall: Wer zahlt?" },
      { type: "p", text: "Verstirbt eine Person, gehen sämtliche Rechte und Pflichten auf die Erben über (§ 1922 BGB). Das schließt auch die Entrümpelung der Wohnung oder des Hauses ein. Die Kosten werden aus der Erbmasse beglichen – reicht diese nicht aus, müssen die Erben aus eigenem Vermögen zahlen, sofern sie das Erbe angenommen haben." },
      {
        type: "ul",
        items: [
          "Mehrere Erben: anteilig nach Erbquote",
          "Erbe ausgeschlagen (§ 1942 BGB): keine Zahlungspflicht",
          "Überschuldeter Nachlass: Nachlassverwaltung beantragen, Haftung begrenzen",
          "Kosten sind als Nachlassverbindlichkeit absetzbar (Erbschaftsteuer)",
        ],
      },
      { type: "h2", text: "2. Entrümpelung bei Mietnomaden oder Räumungsklage" },
      { type: "p", text: "Lässt ein Mieter beim Auszug seinen Hausrat zurück oder wird er gerichtlich geräumt, muss zunächst der Vermieter die Entrümpelung beauftragen. Er kann die Kosten anschließend gegen den Mieter geltend machen (§ 280 BGB, Schadensersatz wegen Pflichtverletzung). In der Praxis bleibt der Vermieter aber oft auf den Kosten sitzen, wenn der Mieter nicht zahlungsfähig ist – die Mietkaution deckt selten alles." },
      {
        type: "ul",
        items: [
          "Hausrat nicht einfach wegwerfen – sonst droht Schadensersatz an den Mieter",
          "Sachen 4–6 Wochen einlagern oder dokumentiert übergeben",
          "Mit Foto- und Video-Dokumentation gegen spätere Forderungen absichern",
          "Bei Räumungstitel: Gerichtsvollzieher hinzuziehen, Berliner Räumung möglich",
        ],
      },
      { type: "h2", text: "3. Entrümpelung im Pflegefall (Umzug ins Heim)" },
      { type: "p", text: "Zieht eine Person ins Pflegeheim, trägt sie selbst die Kosten der Wohnungsauflösung. Reicht das Vermögen nicht aus und ist die Person sozialhilfebedürftig, kann unter Umständen das Sozialamt einspringen (§ 73 SGB XII, sonstige Hilfen in besonderen Lebenslagen). Das ist aber Ermessenssache und muss vorab beantragt werden." },
      { type: "h2", text: "4. Entrümpelung und Sozialamt: Wann wird gezahlt?" },
      { type: "p", text: "Das Sozialamt übernimmt Entrümpelungskosten nur in Ausnahmefällen – etwa wenn die Räumung Voraussetzung für einen Umzug in eine günstigere Wohnung ist (Kosten der Unterkunft, § 22 SGB II) oder bei nachgewiesener Hilfebedürftigkeit. Wichtig: Antrag immer VORHER stellen, sonst keine Übernahme." },
      {
        type: "links",
        title: "Passende Leistungen",
        items: [
          { label: "Haushaltsauflösung (Erbfall)", to: "/haushaltsaufloesung" },
          { label: "Wohnungsentrümpelung", to: "/wohnungsentruempelung" },
          { label: "Hausentrümpelung", to: "/hausentruempelung" },
          { label: "Firmen- & Gewerbeentrümpelung", to: "/firmen-gewerbeentruempelung" },
          { label: "Preise & Festpreise", to: "/preise" },
        ],
      },
      { type: "h2", text: "5. Entrümpelung nach Todesfall: praktische Tipps" },
      {
        type: "ol",
        items: [
          "Vor der Räumung Erbschein oder Vollmacht klären",
          "Persönliche Dokumente, Schmuck und Bargeld zuerst sichern",
          "Wertgegenstände schätzen lassen (Sachverständige des Auktionshauses)",
          "Mietvertrag prüfen: Kündigungsfristen, Renovierungspflichten",
          "Festpreisangebot eines Direktanbieters einholen – schriftlich",
        ],
      },
      {
        type: "quote",
        text: "Im Erbfall ist die größte Falle: Erbe annehmen, ohne den Wert des Nachlasses zu kennen. Im Zweifel zuerst Nachlassverzeichnis erstellen.",
      },
      { type: "h2", text: "6. Können Entrümpelungskosten von der Steuer abgesetzt werden?" },
      {
        type: "ul",
        items: [
          "Im Erbfall: ja, als Nachlassverbindlichkeit (Erbschaftsteuer, § 10 ErbStG)",
          "Bei Vermietung: ja, als Werbungskosten (§ 9 EStG)",
          "Im Privathaushalt: 20 % der Arbeitskosten (max. 4.000 €/Jahr) als haushaltsnahe Dienstleistung (§ 35a EStG) – Rechnung mit Überweisung erforderlich",
        ],
      },
      {
        type: "links",
        title: "Wir kommen in Ihre Region",
        items: [
          { label: "Brieselang", to: "/entruempelung-brieselang" },
          { label: "Falkensee", to: "/entruempelung-falkensee" },
          { label: "Nauen", to: "/entruempelung-nauen" },
          { label: "Oranienburg", to: "/entruempelung-oranienburg" },
          { label: "Hennigsdorf", to: "/entruempelung-hennigsdorf" },
          { label: "Rathenow", to: "/entruempelung-rathenow" },
          { label: "Havelland", to: "/entruempelung-havelland" },
        ],
      },
      { type: "h2", text: "Häufige Fragen" },
      { type: "h3", text: "Wer zahlt die Entrümpelung, wenn das Erbe ausgeschlagen wird?" },
      { type: "p", text: "Dann fällt der Nachlass an die nächsten Erben oder schließlich an den Staat (§ 1936 BGB). Wer ausschlägt, haftet nicht für Entrümpelungskosten." },
      { type: "h3", text: "Muss ich die Wohnung meines verstorbenen Vermieters räumen?" },
      { type: "p", text: "Nein. Der Mietvertrag endet nicht automatisch mit dem Tod des Mieters – Erben übernehmen den Vertrag oder können kündigen (§ 564 BGB). Geräumt werden muss erst, wenn das Mietverhältnis endet." },
      { type: "h3", text: "Was passiert, wenn niemand die Entrümpelung zahlt?" },
      { type: "p", text: "Der Vermieter oder Eigentümer muss vorstrecken und kann seine Forderung später zivilrechtlich geltend machen. Bei Insolvenz oder unbekanntem Aufenthalt des Schuldners bleibt er meist auf den Kosten sitzen." },
      { type: "p", text: "Hinweis: Dieser Ratgeber ersetzt keine Rechtsberatung. Bei komplexen Konstellationen (überschuldeter Nachlass, Erbengemeinschaft mit Streit, Insolvenz) sollten Sie einen Anwalt für Erbrecht konsultieren." },
      { type: "h2", text: "Festpreisangebot nach Erbfall, Pflegefall oder Räumung" },
      { type: "p", text: "Wir kennen die Situation nach einem Todesfall oder einer Räumungsklage – wir arbeiten diskret, schnell und mit verbindlichem Festpreis. Rufen Sie an unter 01579 2639408 oder schreiben Sie per WhatsApp." },
    ],
  },
  // ============================================================
  // GEPLANTE ARTIKEL (publishedAt in Zukunft – automatischer Release)
  // ============================================================
  {
    slug: "messie-wohnung-entruempeln-diskret",
    title: "Messie-Wohnung entrümpeln: Diskret, respektvoll & ohne Vorwurf",
    metaTitle: "Messie-Wohnung entrümpeln im Havelland | Diskret 2026",
    metaDescription:
      "Messie-Wohnung im Havelland entrümpeln lassen: diskret, ohne Vorwurf, mit Festpreis. So läuft es ab, was es kostet, worauf Sie achten sollten. ☎ 01579 2639408",
    excerpt:
      "Eine Messie-Wohnung zu räumen ist heikel – emotional und organisatorisch. Wir zeigen, wie eine respektvolle Räumung im Havelland abläuft, was sie kostet und worauf Angehörige besonders achten sollten.",
    publishedAt: "2026-06-09",
    updatedAt: "2026-06-15",
    readingTimeMin: 7,
    category: "Spezial-Räumungen",
    keywords: [
      "messie wohnung entrümpelung",
      "messie wohnung räumen havelland",
      "messie haushalt auflösen",
      "vermüllte wohnung entrümpeln",
    ],
    content: [
      { type: "p", text: "Eine Messie-Wohnung zu entrümpeln ist mehr als nur Räumen. Es ist eine sensible Aufgabe, bei der Diskretion, Respekt und Erfahrung über alles gehen. Im Havelland sind wir auf solche Räumungen spezialisiert – ohne Vorwurf, ohne Schaulustige, ohne Nachfragen bei Nachbarn. In diesem Ratgeber erfahren Sie, wie der Ablauf aussieht, welche Kosten realistisch sind und worauf Angehörige achten sollten." },
      { type: "h2", text: "Was ist eine Messie-Wohnung?" },
      { type: "p", text: "Von einer Messie-Wohnung spricht man, wenn Räume so stark vollgestellt sind, dass normale Nutzung kaum noch möglich ist: Türen lassen sich nicht öffnen, Böden sind nicht mehr sichtbar, oft kommen Geruchsbelastung, Schädlinge oder Schimmel dazu. Betroffene leiden meist still – die Wohnung ist Symptom, nicht Ursache." },
      { type: "h2", text: "Ablauf einer diskreten Messie-Räumung" },
      { type: "ol", items: [
        "Anonymer Erstkontakt per Telefon oder WhatsApp – wir nennen keine Namen am Telefon.",
        "Kostenlose Besichtigung in zivilen Fahrzeugen (kein Firmenlogo).",
        "Schriftliches Festpreisangebot inkl. Schädlingsbehandlung, falls nötig.",
        "Räumung mit Atemschutz, Handschuhen, Schutzanzügen – professionell und stumm.",
        "Grundreinigung, Geruchsneutralisation, besenreine Übergabe.",
      ] },
      { type: "h2", text: "Was kostet eine Messie-Räumung 2026?" },
      { type: "p", text: "Messie-Räumungen sind durch hohes Volumen, Schutzausrüstung und oft notwendige Reinigung teurer als normale Entrümpelungen. Realistische Preise im Havelland:" },
      { type: "ul", items: [
        "1-Zimmer-Wohnung (Messie-Level mittel): 1.290 – 2.190 €",
        "2-Zimmer-Wohnung (Messie-Level mittel): 1.890 – 3.290 €",
        "3-4-Zimmer-Wohnung: 2.890 – 4.890 €",
        "Aufschlag bei Schädlingen, Fäkalien, Schimmel: +20–40 %",
      ] },
      { type: "h2", text: "Worauf Angehörige achten sollten" },
      { type: "ul", items: [
        "Nichts heimlich entsorgen – das zerstört Vertrauen.",
        "Wenn möglich: Betroffene Person einbinden, auch nur symbolisch.",
        "Wertgegenstände, Dokumente und Fotos vorab sichern lassen.",
        "Therapeutische Begleitung parallel anbieten – Räumung allein löst das Problem nicht.",
      ] },
      { type: "quote", text: "Wir kommen ohne Wertung. Niemand wählt diesen Zustand bewusst – unser Job ist Räumen, nicht Beurteilen." },
      { type: "links", title: "Verwandte Ratgeber", items: [
        { label: "Was kostet eine Entrümpelung?", to: "/blog/was-kostet-eine-entruempelung-preise-2026" },
        { label: "Wohnungsentrümpelung", to: "/wohnungsentruempelung" },
        { label: "Haushaltsauflösung", to: "/haushaltsaufloesung" },
      ] },
      { type: "h2", text: "Häufige Fragen" },
      { type: "h3", text: "Erfahren Nachbarn etwas davon?" },
      { type: "p", text: "Nein. Wir kommen mit zivilen Transportern ohne Firmenlogo. Wir sprechen niemanden im Haus an. Die Räumung wirkt von außen wie ein normaler Umzug." },
      { type: "h3", text: "Können Sie auch Schädlinge bekämpfen?" },
      { type: "p", text: "Wir arbeiten mit zertifizierten Partnern für Schädlingsbekämpfung zusammen und koordinieren das für Sie – alles aus einer Hand." },
      { type: "h3", text: "Wer trägt die Kosten?" },
      { type: "p", text: "In der Regel die betroffene Person, deren Betreuer oder bei Räumungsklage der Vermieter (mit Rückforderung). Details in unserem Ratgeber 'Wer trägt die Kosten einer Entrümpelung?'." },
      { type: "h2", text: "Diskrete Besichtigung anfragen" },
      { type: "p", text: "Rufen Sie an unter 01579 2639408 oder schreiben Sie per WhatsApp. Wir melden uns binnen 30 Minuten zurück – diskret, ohne Wertung, mit Festpreis." },
    ],
  },
  {
    slug: "nachlass-entruempelung-erben-pflichten",
    title: "Nachlass-Entrümpelung nach Todesfall: Was Erben wissen müssen",
    metaTitle: "Nachlass entrümpeln nach Todesfall | Pflichten & Kosten 2026",
    metaDescription:
      "Nachlass-Entrümpelung nach Todesfall: Pflichten der Erben, Kosten, Fristen, Steuer. Klarer Ratgeber 2026 mit Festpreisbeispielen aus dem Havelland. ☎ 01579 2639408",
    excerpt:
      "Nach einem Todesfall stehen Angehörige plötzlich vor einer leeren Wohnung voller Erinnerungen. Wir erklären die Pflichten der Erben, realistische Kosten und wie eine respektvolle Nachlassauflösung im Havelland abläuft.",
    publishedAt: "2026-07-22",
    updatedAt: "2026-07-15",
    readingTimeMin: 7,
    category: "Nachlass & Erben",
    keywords: [
      "nachlass entrümpelung",
      "erben wohnung räumen",
      "haushaltsauflösung todesfall",
      "nachlass auflösen kosten",
    ],
    content: [
      { type: "p", text: "Ein Todesfall ist Ausnahmezustand. Und mittendrin kommt die Frage: Wer räumt die Wohnung? Wer zahlt? Wie schnell muss alles raus? Dieser Ratgeber gibt Erben im Havelland klare Antworten – ohne Juristen-Deutsch, mit echten Festpreisbeispielen." },
      { type: "h2", text: "Wer ist verpflichtet zu räumen?" },
      { type: "p", text: "Mit dem Erbe übernehmen Sie Rechte UND Pflichten – auch die Räumung der Wohnung (§ 1922 BGB). Bei einer Erbengemeinschaft tragen alle Erben die Kosten gemeinsam, anteilig zu ihrer Erbquote. Wer das Erbe ausschlägt (Frist: 6 Wochen ab Kenntnis), ist nicht zur Räumung verpflichtet." },
      { type: "h2", text: "Welche Fristen gelten?" },
      { type: "ul", items: [
        "Mietwohnung: Kündigung durch Erben binnen 1 Monats möglich (§ 564 BGB), Räumung zum Mietende.",
        "Eigentumswohnung: Keine gesetzliche Frist – aber Hausgeld läuft weiter.",
        "Erbausschlagung: 6 Wochen ab Kenntnis vom Erbfall (§ 1944 BGB).",
      ] },
      { type: "h2", text: "Realistische Kosten für Nachlass-Räumung 2026" },
      { type: "ul", items: [
        "1-Zimmer-Wohnung: 690 – 1.290 €",
        "2-3-Zimmer-Wohnung: 1.290 – 2.190 €",
        "Einfamilienhaus mit Keller & Dachboden: 2.490 – 4.500 €",
        "Mit Antiquitäten-Anrechnung: −100 bis −800 €",
      ] },
      { type: "h2", text: "Steuerlich absetzbar?" },
      { type: "p", text: "Ja – Nachlass-Räumungen sind als Nachlassverbindlichkeit von der Erbschaftsteuer abziehbar (§ 10 ErbStG). Bewahren Sie alle Rechnungen auf und übergeben Sie diese dem Finanzamt." },
      { type: "h2", text: "So läuft eine respektvolle Nachlass-Räumung ab" },
      { type: "ol", items: [
        "Sichten: Wertgegenstände, Dokumente, Fotos und Schmuck identifizieren.",
        "Vorsortieren: Was bleibt in der Familie, was wird gespendet, was entsorgt?",
        "Kostenlose Besichtigung mit Festpreisangebot.",
        "Räumung – mit Pietät und ohne Hektik.",
        "Besenreine Übergabe an Vermieter oder Käufer.",
      ] },
      { type: "quote", text: "Wir arbeiten leise. In jeder Schublade kann eine Erinnerung liegen – wir behandeln jede Wohnung so, als wäre es die unserer eigenen Großmutter." },
      { type: "links", title: "Weiterführende Ratgeber", items: [
        { label: "Wer trägt die Kosten?", to: "/blog/wer-traegt-kosten-entruempelung" },
        { label: "Haushaltsauflösung", to: "/haushaltsaufloesung" },
        { label: "Wertanrechnung", to: "/blog/entruempelung-mit-wertanrechnung" },
      ] },
      { type: "h2", text: "Häufige Fragen" },
      { type: "h3", text: "Was passiert mit Dokumenten und Fotos?" },
      { type: "p", text: "Wir sortieren alle persönlichen Dokumente, Fotos und Briefe separat in Kartons und übergeben sie der Familie – nichts wird ungefragt entsorgt." },
      { type: "h3", text: "Müssen alle Erben anwesend sein?" },
      { type: "p", text: "Nein. Ein bevollmächtigter Erbe (Vollmacht der Erbengemeinschaft) reicht für die Beauftragung." },
      { type: "h3", text: "Wie schnell können Sie räumen?" },
      { type: "p", text: "Besichtigung binnen 24–48 Stunden, Räumung in der Regel binnen 5–10 Tagen. Express-Termine möglich." },
      { type: "h2", text: "Festpreisangebot für Nachlass-Räumung anfordern" },
      { type: "p", text: "Wir kennen die emotionale Situation. Rufen Sie an unter 01579 2639408 oder schreiben Sie per WhatsApp – wir nehmen uns Zeit für Sie." },
    ],
  },
  {
    slug: "entruempelung-steuerlich-absetzen",
    title: "Entrümpelung steuerlich absetzen 2026: So sparen Sie bis 4.000 € pro Jahr",
    metaTitle: "Entrümpelung steuerlich absetzbar? | Bis 4.000 € sparen 2026",
    metaDescription:
      "Entrümpelung von der Steuer absetzen: Privat, Erbfall, Vermietung. Bis 4.000 € pro Jahr sparen. Klarer Ratgeber 2026 mit Beispielen. ☎ 01579 2639408",
    excerpt:
      "Eine Entrümpelung lässt sich in vielen Fällen steuerlich absetzen – im Privathaushalt bis 4.000 € pro Jahr, im Erbfall sogar komplett. Wir zeigen die drei Szenarien mit Beispielen und Tipps zur Rechnungserstellung.",
    publishedAt: "2026-08-04",
    updatedAt: "2026-08-15",
    readingTimeMin: 6,
    category: "Steuern & Recht",
    keywords: [
      "entrümpelung steuerlich absetzbar",
      "haushaltsauflösung steuer",
      "haushaltsnahe dienstleistung entrümpelung",
      "nachlass entrümpelung steuer",
    ],
    content: [
      { type: "p", text: "Eine Entrümpelung ist 2026 in drei Konstellationen steuerlich absetzbar: im Privathaushalt (haushaltsnahe Dienstleistung), nach einem Todesfall (Nachlassverbindlichkeit) und bei Vermietung (Werbungskosten). Wir zeigen, wie Sie bis zu 4.000 € pro Jahr ans Finanzamt zurückholen." },
      { type: "h2", text: "Variante 1: Haushaltsnahe Dienstleistung (§ 35a EStG)" },
      { type: "p", text: "Bei einer Entrümpelung im eigenen Privathaushalt können Sie 20 % der Arbeitskosten direkt von der Steuerschuld abziehen – maximal 4.000 € pro Jahr. Das gilt für Mieter und Eigentümer." },
      { type: "ul", items: [
        "Voraussetzung: Rechnung mit Aufteilung Arbeit / Material",
        "Bezahlung per Überweisung (kein Bargeld!)",
        "Eintrag in Anlage 'haushaltsnahe Dienstleistungen' der Steuererklärung",
      ] },
      { type: "h3", text: "Beispiel: Wohnung in Falkensee" },
      { type: "p", text: "Festpreis 1.890 € (davon 1.500 € Arbeit, 390 € Entsorgung). 20 % von 1.500 € = 300 € Steuererstattung. Aufwand: 5 Minuten in der Steuererklärung." },
      { type: "h2", text: "Variante 2: Nachlassverbindlichkeit (§ 10 ErbStG)" },
      { type: "p", text: "Nach einem Erbfall sind Räumungskosten in voller Höhe von der Erbschaftsteuer abziehbar. Auch Reinigung, Entsorgung und Schadstoffsanierung zählen dazu." },
      { type: "ul", items: [
        "Voraussetzung: Rechnung lautet auf den/die Erben",
        "Beleg dem Finanzamt mit der Erbschaftsteuererklärung einreichen",
        "Auch nachträglich möglich (Frist: 4 Jahre)",
      ] },
      { type: "h2", text: "Variante 3: Werbungskosten bei Vermietung (§ 9 EStG)" },
      { type: "p", text: "Vermieter setzen Entrümpelungskosten zwischen zwei Mietverhältnissen voll als Werbungskosten ab. Das mindert die Einkünfte aus Vermietung und Verpachtung 1:1." },
      { type: "h2", text: "Was ist nicht absetzbar?" },
      { type: "ul", items: [
        "Räumung einer leerstehenden Ferienwohnung ohne Vermietungsabsicht",
        "Räumung vor Verkauf der eigenen Immobilie (private Veräußerung)",
        "Materialkosten (Container, Entsorgung) bei § 35a EStG – nur Arbeit zählt",
      ] },
      { type: "h2", text: "So muss die Rechnung aussehen" },
      { type: "p", text: "Damit das Finanzamt mitspielt, brauchen Sie eine ordentliche Rechnung mit:" },
      { type: "ul", items: [
        "Vollständiger Name und Adresse des Anbieters",
        "Rechnungsnummer und Datum",
        "Klare Trennung Arbeitskosten / Materialkosten",
        "Ausgewiesene 19 % Mehrwertsteuer",
        "Hinweis: 'Bezahlung per Überweisung'",
      ] },
      { type: "p", text: "Wir stellen alle Rechnungen so aus, dass sie sofort beim Finanzamt durchgehen – fragen Sie einfach bei der Buchung danach." },
      { type: "quote", text: "Wer die Rechnung richtig stellt, holt sich gerne 300–600 € pro Räumung vom Staat zurück. Kostet 0 Minuten Mehraufwand." },
      { type: "links", title: "Verwandte Ratgeber", items: [
        { label: "Was kostet eine Entrümpelung?", to: "/blog/was-kostet-eine-entruempelung-preise-2026" },
        { label: "Wer trägt die Kosten?", to: "/blog/wer-traegt-kosten-entruempelung" },
        { label: "Nachlass-Entrümpelung", to: "/blog/nachlass-entruempelung-erben-pflichten" },
      ] },
      { type: "h2", text: "Häufige Fragen" },
      { type: "h3", text: "Muss die Wohnung im selben Haushalt sein wie meine?" },
      { type: "p", text: "Nein. Auch die Räumung der Wohnung eines pflegebedürftigen Angehörigen zählt, wenn Sie die Kosten tragen." },
      { type: "h3", text: "Geht das auch bei Barzahlung?" },
      { type: "p", text: "Nein. § 35a EStG verlangt zwingend Überweisung – bei Bargeld erkennt das Finanzamt den Abzug nicht an." },
      { type: "h3", text: "Hinweis" },
      { type: "p", text: "Dieser Ratgeber ersetzt keine Steuerberatung. Bei komplexen Fällen sprechen Sie mit Ihrem Steuerberater." },
      { type: "h2", text: "Rechnung steuerkonform anfordern" },
      { type: "p", text: "Rufen Sie an unter 01579 2639408 oder schreiben Sie per WhatsApp. Wir stellen jede Rechnung sofort steuerkonform aus." },
    ],
  },
  {
    slug: "sperrmuell-oder-entruempelung-vergleich",
    title: "Sperrmüll oder Entrümpelung? Vergleich, Kosten & Entscheidungshilfe 2026",
    metaTitle: "Sperrmüll oder Entrümpelung? | Vergleich & Kosten 2026",
    metaDescription:
      "Sperrmüll oder Entrümpelung – was lohnt sich wann? Klarer Vergleich mit Kosten, Aufwand und Beispielen aus dem Havelland. ☎ 01579 2639408",
    excerpt:
      "Reicht der kostenlose Sperrmüll oder brauche ich eine Entrümpelungsfirma? Dieser Vergleich zeigt klar, ab wann sich ein Profi lohnt – mit Kosten, Aufwand und Beispielen aus dem Havelland.",
    publishedAt: "2026-09-17",
    updatedAt: "2026-09-15",
    readingTimeMin: 6,
    category: "Ratgeber & Vergleich",
    keywords: [
      "sperrmüll oder entrümpelung",
      "unterschied sperrmüll entrümpelung",
      "sperrmüll havelland kosten",
      "wann entrümpelungsfirma",
    ],
    content: [
      { type: "p", text: "Sperrmüll ist im Havelland kostenlos – aber er hat Grenzen. Sobald es um Möbeldemontage, große Mengen, mehrere Etagen oder Sondermüll geht, lohnt sich der Profi schnell. Dieser Ratgeber zeigt klar, wann was Sinn macht." },
      { type: "h2", text: "Sperrmüll im Havelland: Was geht, was nicht?" },
      { type: "p", text: "Die kommunale Abfallwirtschaft holt Sperrmüll auf Anmeldung kostenlos ab – allerdings mit Einschränkungen:" },
      { type: "ul", items: [
        "Maximal 3–4 m³ pro Haushalt und Termin",
        "Nur bestimmte Möbel und Hausrat – kein Bauschutt, kein Sondermüll",
        "Keine Demontage – muss vor die Tür gestellt werden",
        "Wartezeit oft 2–6 Wochen auf einen Termin",
        "Elektrogeräte separat anmelden",
      ] },
      { type: "h2", text: "Wann reicht Sperrmüll?" },
      { type: "ul", items: [
        "Einzelne Möbelstücke (Sofa, Schrank, Bett)",
        "Sie können selbst tragen und vor die Tür stellen",
        "Kein Termindruck (Wartezeit OK)",
        "Kleine Mengen unter 3 m³",
      ] },
      { type: "h2", text: "Wann brauchen Sie eine Entrümpelungsfirma?" },
      { type: "ul", items: [
        "Ganze Wohnung, Keller, Dachboden oder Haus",
        "Möbel müssen demontiert oder zerlegt werden",
        "Über mehrere Etagen, ohne Aufzug",
        "Termindruck (Mietende, Verkauf, Erbfall)",
        "Sondermüll: Farben, Asbest, alte Heizöltanks",
        "Sie können oder wollen körperlich nicht selbst ran",
      ] },
      { type: "h2", text: "Kostenvergleich 2026" },
      { type: "ul", items: [
        "Sperrmüll Havelland: 0 € (bis 3 m³, Selbsttransport zur Straße)",
        "Containerdienst (10 m³): 280 – 450 € (Sie müssen selbst befüllen)",
        "Komplettentrümpelung Wohnung (Profi): 690 – 2.690 € (alles inklusive)",
      ] },
      { type: "h2", text: "Drei reale Beispiele aus dem Havelland" },
      { type: "h3", text: "Beispiel 1: Sofa in Brieselang" },
      { type: "p", text: "Einzelnes Sofa, Familie kann selbst rausstellen. Sperrmüll genügt – 0 €." },
      { type: "h3", text: "Beispiel 2: Keller in Falkensee" },
      { type: "p", text: "8 m³ alte Möbel und Kartons, 2. Untergeschoss, kein Aufzug. Sperrmüll bringt es nicht – Profi-Entrümpelung 349 €." },
      { type: "h3", text: "Beispiel 3: 3-Zimmer-Wohnung Nauen nach Auszug" },
      { type: "p", text: "Komplette Wohnung muss in 7 Tagen geräumt sein, besenrein. Sperrmüll-Termin gibt's frühestens in 3 Wochen. Profi-Entrümpelung 1.690 € inkl. Übergabe." },
      { type: "quote", text: "Sperrmüll ist super, solange Sie Zeit haben, körperlich fit sind und unter 3 m³ bleiben. Drüber wird der Profi schnell günstiger – wegen Zeit, Rücken und Nerven." },
      { type: "links", title: "Verwandte Ratgeber", items: [
        { label: "Was kostet eine Entrümpelung?", to: "/blog/was-kostet-eine-entruempelung-preise-2026" },
        { label: "Kellerentrümpelung", to: "/kellerentruempelung" },
        { label: "Wohnungsentrümpelung", to: "/wohnungsentruempelung" },
      ] },
      { type: "h2", text: "Häufige Fragen" },
      { type: "h3", text: "Wie lange dauert ein Sperrmüll-Termin im Havelland?" },
      { type: "p", text: "Aktuell 2–6 Wochen Wartezeit, je nach Saison. Im Frühjahr und Herbst länger." },
      { type: "h3", text: "Was passiert mit Elektrogeräten?" },
      { type: "p", text: "Elektrogeräte müssen separat angemeldet oder bei der kommunalen Sammelstelle abgegeben werden. Beim Profi: alles in einem Abwasch." },
      { type: "h3", text: "Können Sie nur einen Teil räumen?" },
      { type: "p", text: "Ja. Wir machen auch Teilräumungen – zum Beispiel nur Keller oder nur ein Zimmer." },
      { type: "h2", text: "Festpreis für Ihre Räumung anfragen" },
      { type: "p", text: "Rufen Sie an unter 01579 2639408 oder schreiben Sie per WhatsApp. Kostenlose Besichtigung, verbindlicher Festpreis – im gesamten Havelland." },
    ],
  },
  {
    slug: "keller-entruempeln-in-einem-tag",
    title: "Keller entrümpeln in 1 Tag: Ablauf, Preise & Tipps für den Herbstputz 2026",
    metaTitle: "Keller entrümpeln in 1 Tag | Ablauf & Preise 2026",
    metaDescription:
      "Keller entrümpeln in nur einem Tag: realistische Preise, klarer Ablauf und Profi-Tipps für den Herbstputz im Havelland. Festpreis ab 299 €. ☎ 01579 2639408",
    excerpt:
      "Der Herbst ist die beste Zeit für die Keller-Entrümpelung. Wir zeigen, wie eine Räumung in einem Tag abläuft, was 2026 realistisch kostet und mit welchen Tricks Sie schneller fertig sind.",
    publishedAt: "2026-10-06",
    updatedAt: "2026-10-15",
    readingTimeMin: 6,
    category: "Saisonale Ratgeber",
    keywords: [
      "keller entrümpeln",
      "keller entrümpelung kosten",
      "keller räumen havelland",
      "keller ausmisten herbst",
    ],
    content: [
      { type: "p", text: "Im Herbst werden Keller wieder zur Heizraum-Logistik – höchste Zeit, das alte Chaos loszuwerden. Eine professionelle Keller-Entrümpelung im Havelland dauert in der Regel nur einen Tag, kostet ab 299 € und endet mit besenreinem Boden. Dieser Ratgeber zeigt Ablauf, Preise und die wichtigsten Tipps." },
      { type: "h2", text: "Warum gerade im Herbst entrümpeln?" },
      { type: "ul", items: [
        "Vor dem Winter: Heizung, Pelletlager und Vorräte brauchen Platz",
        "Trockene Witterung: Möbel bleiben sauber beim Transport",
        "Kein Schimmelrisiko mehr durch Sommerfeuchte",
        "Vor Weihnachten Ordnung – entspannte Feiertage",
      ] },
      { type: "h2", text: "Was kostet eine Keller-Entrümpelung 2026?" },
      { type: "ul", items: [
        "Kleiner Keller (bis 10 m³): 299 – 590 €",
        "Mittlerer Keller (10–20 m³): 590 – 990 €",
        "Großer Keller / mehrere Räume: 990 – 1.690 €",
        "Aufpreis für Sondermüll (Farben, Öl): nach Aufwand",
      ] },
      { type: "h2", text: "Ablauf in 1 Tag" },
      { type: "ol", items: [
        "Morgens 8 Uhr: 2-Mann-Team trifft ein, schützt Treppenhaus und Flure.",
        "Sichtung: Was kommt mit, was bleibt, was geht zur Wertanrechnung.",
        "Räumung etagenweise mit Transporter direkt vor der Tür.",
        "Zwischensortierung: Metall, Elektro, Sperrmüll, Restmüll.",
        "Nachmittags: Besenreine Übergabe und schriftliche Abnahme.",
      ] },
      { type: "h2", text: "5 Profi-Tipps für die Keller-Entrümpelung" },
      { type: "ol", items: [
        "Vor dem Termin: Wertgegenstände und Dokumente in beschriftete Kisten packen.",
        "Alte Farbeimer, Lacke und Öle vorab sortieren – das ist Sondermüll.",
        "Metalle separat: Heizkörper, Rohre, Kabel bringen Wertanrechnung.",
        "Bilder vom Vorher-Zustand machen – hilft bei Vermieter-Streit.",
        "Festpreis nach Volumen vereinbaren – nie nach Stunden!",
      ] },
      { type: "quote", text: "Ein durchschnittlicher Keller im Havelland ist mit 2 Mann in 4–6 Stunden komplett geräumt. Wer länger braucht, hat zu viele Pausen gemacht." },
      { type: "links", title: "Verwandte Ratgeber", items: [
        { label: "Kellerentrümpelung", to: "/kellerentruempelung" },
        { label: "Was kostet eine Entrümpelung?", to: "/blog/was-kostet-eine-entruempelung-preise-2026" },
        { label: "Wertanrechnung nutzen", to: "/blog/entruempelung-mit-wertanrechnung" },
      ] },
      { type: "h2", text: "Häufige Fragen" },
      { type: "h3", text: "Müssen Sie ins Treppenhaus dürfen?" },
      { type: "p", text: "Bei Mehrfamilienhäusern reicht meist die normale Hausordnung. Bei großen Mengen sprechen wir vorher mit der Hausverwaltung." },
      { type: "h3", text: "Was passiert mit Heizkörpern und Metallrohren?" },
      { type: "p", text: "Werden separat zum Schrotthandel gebracht – der Erlös fließt in die Wertanrechnung." },
      { type: "h3", text: "Können Sie auch nur Teilbereiche räumen?" },
      { type: "p", text: "Ja, einzelne Kellerräume oder Boxen sind ab 199 € machbar." },
      { type: "h2", text: "Festpreis für Ihre Keller-Räumung anfragen" },
      { type: "p", text: "Rufen Sie an unter 01579 2639408 oder schreiben Sie per WhatsApp. Besichtigung kostenlos, Räumung meist in 1 Tag erledigt." },
    ],
  },
  {
    slug: "garage-schuppen-entruempeln-vor-winter",
    title: "Garage & Schuppen entrümpeln vor dem Winter: Preise & Ablauf 2026",
    metaTitle: "Garage & Schuppen entrümpeln vor Winter | Preise 2026",
    metaDescription:
      "Garage und Schuppen vor dem Winter entrümpeln lassen: Preise, Ablauf, Wertanrechnung für Werkzeug und Metall. Festpreis im Havelland. ☎ 01579 2639408",
    excerpt:
      "Bevor Schnee und Frost kommen, lohnt sich die Garagen- oder Schuppen-Räumung. Wir zeigen Preise, Ablauf und wie Sie mit alten Werkzeugen und Metall bares Geld zurückbekommen.",
    publishedAt: "2026-11-19",
    updatedAt: "2026-11-15",
    readingTimeMin: 6,
    category: "Saisonale Ratgeber",
    keywords: [
      "garage entrümpeln preise",
      "schuppen entrümpelung",
      "gartenhaus räumen",
      "werkstatt auflösen",
    ],
    content: [
      { type: "p", text: "Garagen, Schuppen und Gartenhäuser sind im Havelland klassische Sammelstellen für alte Werkzeuge, Reifen, Gartenmöbel und Altmetall. Vor dem Winter ist die letzte Chance, ohne Schnee und Eis zu räumen. Wir zeigen die Preise 2026, den Ablauf und welche Wertanrechnung drin ist." },
      { type: "h2", text: "Was wird häufig in Garagen entsorgt?" },
      { type: "ul", items: [
        "Alte Reifen und Felgen",
        "Defekte Gartengeräte, Rasenmäher",
        "Altöl, Batterien, Lacke (Sondermüll!)",
        "Werkbänke, Werkzeug, Kabelreste",
        "Gartenmöbel, Sonnenschirme, Markisen",
      ] },
      { type: "h2", text: "Preise 2026: Garage & Schuppen entrümpeln" },
      { type: "ul", items: [
        "Einzelgarage (bis 15 m³): 390 – 690 €",
        "Doppelgarage / großer Schuppen: 690 – 1.190 €",
        "Werkstatt mit Maschinen: 990 – 1.890 €",
        "Gartenhaus inkl. Demontage: ab 590 €",
      ] },
      { type: "h2", text: "Wertanrechnung: Was bringt Geld zurück?" },
      { type: "ul", items: [
        "Markenwerkzeug (Hilti, Bosch Profi, Festool) – Ankaufpreis",
        "Altmetall, Kupfer, Edelstahl – nach Tagespreis",
        "Funktionstüchtige Gartengeräte – bis 100 € pro Stück",
        "Alte Motorräder, Mopeds, Roller – nach Bewertung",
      ] },
      { type: "h2", text: "Ablauf einer Garagen-Räumung" },
      { type: "ol", items: [
        "Kostenlose Besichtigung – meist binnen 24 Stunden möglich.",
        "Schriftliches Festpreisangebot mit Wertanrechnung.",
        "Räumung an einem Tag mit eigenem Transporter.",
        "Sondermüll wird separat ordnungsgemäß entsorgt.",
        "Besenreine Übergabe.",
      ] },
      { type: "quote", text: "Garagen unterschätzt jeder. Was nach 'einem halben Tag' aussieht, sind schnell 15 m³ – aber mit guter Vorbereitung kein Problem." },
      { type: "links", title: "Verwandte Ratgeber", items: [
        { label: "Schrottabholung", to: "/schrottabholung" },
        { label: "Wertanrechnung", to: "/blog/entruempelung-mit-wertanrechnung" },
        { label: "Sperrmüll oder Entrümpelung?", to: "/blog/sperrmuell-oder-entruempelung-vergleich" },
      ] },
      { type: "h2", text: "Häufige Fragen" },
      { type: "h3", text: "Was passiert mit Altöl und alten Lacken?" },
      { type: "p", text: "Wird als Sondermüll fachgerecht entsorgt – auf Wunsch mit Entsorgungsnachweis." },
      { type: "h3", text: "Demontieren Sie auch das Gartenhaus selbst?" },
      { type: "p", text: "Ja. Holz- und Blechhütten bauen wir auf Wunsch ab und entsorgen die Reste." },
      { type: "h3", text: "Können Sie alte Reifen mitnehmen?" },
      { type: "p", text: "Ja, Reifen werden gegen geringen Aufschlag (2–4 € pro Reifen) fachgerecht entsorgt." },
      { type: "h2", text: "Vor dem Winter Festpreis sichern" },
      { type: "p", text: "Rufen Sie an unter 01579 2639408 oder schreiben Sie per WhatsApp – Besichtigung kostenlos, Räumung meist innerhalb einer Woche." },
    ],
  },
  {
    slug: "entruempelung-jahresende-steuervorteil",
    title: "Entrümpelung zum Jahresende: Steuervorteil noch in 2026 sichern",
    metaTitle: "Entrümpelung Dezember 2026 | Steuervorteil sichern",
    metaDescription:
      "Entrümpelung noch in 2026 erledigen und Steuervorteil sichern: Bis 4.000 € absetzen. Express-Termine bis 30.12. im Havelland. ☎ 01579 2639408",
    excerpt:
      "Wer seine Entrümpelung noch bis zum 31. Dezember 2026 bezahlt, kann den Steuervorteil noch für 2026 nutzen. Wir zeigen, wie Sie kurzfristig einen Termin bekommen – und worauf das Finanzamt achtet.",
    publishedAt: "2026-12-08",
    updatedAt: "2026-12-15",
    readingTimeMin: 5,
    category: "Steuern & Recht",
    keywords: [
      "entrümpelung dezember",
      "entrümpelung jahresende steuer",
      "haushaltsnahe dienstleistung jahresende",
      "entrümpelung kurzfristig",
    ],
    content: [
      { type: "p", text: "Wer noch bis zum 31. Dezember 2026 die Rechnung für seine Entrümpelung bezahlt, kann den Betrag in der Steuererklärung für 2026 geltend machen – und spart bis zu 4.000 €. Im Havelland sind Express-Termine bis Weihnachten noch möglich, aber die Slots werden knapp." },
      { type: "h2", text: "Warum lohnt sich das Jahresende?" },
      { type: "ul", items: [
        "20 % der Arbeitskosten direkt von der Steuerschuld absetzbar (§ 35a EStG)",
        "Maximal 4.000 € pro Jahr Steuerersparnis",
        "Zählt das Zahlungsdatum, nicht das Räumungsdatum",
        "Nur möglich bei Überweisung (kein Bargeld!)",
      ] },
      { type: "h2", text: "Ablauf für Express-Termine im Dezember" },
      { type: "ol", items: [
        "Anruf oder WhatsApp – wir prüfen freie Slots binnen 30 Minuten.",
        "Besichtigung in der gleichen Woche.",
        "Festpreisangebot innerhalb von 24 Stunden schriftlich.",
        "Räumung bis spätestens 23.12. – Rechnung sofort nach Räumung.",
        "Überweisung bis 31.12. = Steuervorteil 2026 gesichert.",
      ] },
      { type: "h2", text: "Was muss auf der Rechnung stehen?" },
      { type: "ul", items: [
        "Klare Trennung: Arbeitskosten / Materialkosten",
        "Hinweis 'Bezahlung per Überweisung'",
        "Vollständige Adresse von Auftraggeber und Anbieter",
        "Ausgewiesene 19 % MwSt.",
      ] },
      { type: "h2", text: "Rechenbeispiel" },
      { type: "p", text: "Festpreis 2.490 € (davon 2.000 € Arbeit). 20 % von 2.000 € = 498 € Steuererstattung in 2026. Wer im Januar zahlt, muss bis 2027 warten." },
      { type: "quote", text: "Im Dezember rufen viele an, die das Steuerthema vergessen haben. Wir versuchen, jeden noch reinzubekommen – aber ab 20.12. wird's eng." },
      { type: "links", title: "Verwandte Ratgeber", items: [
        { label: "Entrümpelung steuerlich absetzen", to: "/blog/entruempelung-steuerlich-absetzen" },
        { label: "Was kostet eine Entrümpelung?", to: "/blog/was-kostet-eine-entruempelung-preise-2026" },
        { label: "Wohnungsentrümpelung", to: "/wohnungsentruempelung" },
      ] },
      { type: "h2", text: "Häufige Fragen" },
      { type: "h3", text: "Reicht ein Überweisungs-Avis?" },
      { type: "p", text: "Ja – entscheidend ist das Wertstellungsdatum. Online-Überweisungen bis 31.12. zählen für 2026." },
      { type: "h3", text: "Geht das auch zwischen den Jahren?" },
      { type: "p", text: "Räumung ja, aber die Zahlung muss spätestens am 31.12. ausgeführt sein. Sonst rutscht der Steuervorteil ins Folgejahr." },
      { type: "h3", text: "Hinweis" },
      { type: "p", text: "Dieser Ratgeber ersetzt keine Steuerberatung. Sprechen Sie bei Unsicherheit mit Ihrem Steuerberater." },
      { type: "h2", text: "Jetzt Dezember-Slot sichern" },
      { type: "p", text: "Rufen Sie an unter 01579 2639408 oder schreiben Sie per WhatsApp – wir prüfen freie Termine sofort." },
    ],
  },
  {
    slug: "wohnungsaufloesung-bei-umzug-ins-pflegeheim",
    title: "Wohnung auflösen bei Umzug ins Pflegeheim: Ablauf, Kosten, Tipps 2026",
    metaTitle: "Wohnungsauflösung Pflegeheim | Ablauf & Kosten 2026",
    metaDescription:
      "Wohnung auflösen bei Umzug ins Pflegeheim: Pflichten, Kosten, Förderung durch Pflegekasse. Diskreter Festpreis im Havelland. ☎ 01579 2639408",
    excerpt:
      "Der Umzug eines Angehörigen ins Pflegeheim bringt viele Pflichten mit sich – auch die Wohnungsauflösung. Wir zeigen den Ablauf, realistische Kosten und welche Zuschüsse möglich sind.",
    publishedAt: "2027-01-13",
    updatedAt: "2027-01-15",
    readingTimeMin: 7,
    category: "Pflege & Senioren",
    keywords: [
      "wohnungsauflösung pflegeheim",
      "wohnung räumen pflegefall",
      "haushaltsauflösung senioren",
      "umzug pflegeheim wohnung räumen",
    ],
    content: [
      { type: "p", text: "Wenn ein Angehöriger ins Pflegeheim zieht, bleibt oft nur wenig Zeit, die alte Wohnung aufzulösen. Mietverträge laufen weiter, die Pflegekasse wartet auf Unterlagen, und emotional ist es ohnehin schwer. Wir zeigen, wie eine Wohnungsauflösung im Pflegefall im Havelland abläuft – respektvoll, schnell, mit Festpreis." },
      { type: "h2", text: "Welche Fristen sind wichtig?" },
      { type: "ul", items: [
        "Mietvertrag: 3 Monate Kündigungsfrist (§ 573c BGB)",
        "Sonderkündigungsrecht bei Pflegebedürftigkeit: NEIN – außer im Mietvertrag vereinbart",
        "Lösung: Nachmieter stellen verkürzt die Kündigungsfrist oft auf wenige Wochen",
        "Pflegekasse: Eigenanteil läuft sofort ab Heimplatz-Antritt",
      ] },
      { type: "h2", text: "Kosten 2026 für eine Pflegefall-Wohnungsauflösung" },
      { type: "ul", items: [
        "1-Zimmer-Wohnung: 690 – 1.190 €",
        "2-Zimmer-Wohnung: 1.190 – 1.890 €",
        "3-4-Zimmer-Wohnung: 1.690 – 2.690 €",
        "Mit Antiquitäten-Anrechnung: bis −800 €",
      ] },
      { type: "h2", text: "Zuschüsse: Was zahlt die Pflegekasse?" },
      { type: "p", text: "Die Pflegekasse zahlt keine Entrümpelungskosten direkt. Aber: Wenn ein Wohnumfeld-Anpassungs-Zuschuss (bis 4.180 € pro Maßnahme, § 40 SGB XI) bewilligt wurde, können damit verbundene Räumungskosten teils gefördert werden – fragen Sie konkret bei Ihrer Kasse nach." },
      { type: "h2", text: "Ablauf im Pflegefall" },
      { type: "ol", items: [
        "Wertgegenstände, Dokumente, Schmuck und Fotos sichern.",
        "Persönliche Lieblingsstücke ins Heimzimmer mitnehmen.",
        "Kostenlose Besichtigung mit Angehörigen – Festpreisangebot.",
        "Räumung mit Pietät, ohne Hektik.",
        "Besenreine Übergabe an Vermieter – auch wir koordinieren das mit der Hausverwaltung.",
      ] },
      { type: "h2", text: "Was passiert mit den Möbeln?" },
      { type: "ul", items: [
        "Gut erhaltene Möbel: Spende an karitative Einrichtungen (auf Wunsch)",
        "Antiquitäten: Wertanrechnung möglich",
        "Restmüll und Sperrgut: fachgerechte Entsorgung",
        "Erinnerungsstücke: separat verpackt und übergeben",
      ] },
      { type: "quote", text: "Im Pflegefall geht es um mehr als Möbel. Wir nehmen uns Zeit, hören zu und arbeiten so leise wie möglich." },
      { type: "links", title: "Verwandte Ratgeber", items: [
        { label: "Haushaltsauflösung", to: "/haushaltsaufloesung" },
        { label: "Wer trägt die Kosten?", to: "/blog/wer-traegt-kosten-entruempelung" },
        { label: "Entrümpelung steuerlich absetzen", to: "/blog/entruempelung-steuerlich-absetzen" },
      ] },
      { type: "h2", text: "Häufige Fragen" },
      { type: "h3", text: "Wer entscheidet über die Wohnungsauflösung?" },
      { type: "p", text: "Bei vollem Einwilligungsvermögen: die Person selbst. Bei Demenz oder rechtlicher Betreuung: der gerichtlich bestellte Betreuer oder Bevollmächtigte (Vorsorgevollmacht)." },
      { type: "h3", text: "Kann ich die Kosten steuerlich absetzen?" },
      { type: "p", text: "Ja – wenn Sie als Angehöriger die Kosten tragen, gilt § 35a EStG (20 % auf Arbeitskosten)." },
      { type: "h3", text: "Wie schnell können Sie räumen?" },
      { type: "p", text: "Besichtigung binnen 24–48 Stunden, Räumung in der Regel binnen 5–10 Tagen." },
      { type: "h2", text: "Diskrete Beratung im Pflegefall" },
      { type: "p", text: "Rufen Sie an unter 01579 2639408 oder schreiben Sie per WhatsApp. Wir nehmen uns Zeit – versprochen." },
    ],
  },
  {
    slug: "entruempelung-mit-schadstoffen-asbest-oel",
    title: "Entrümpelung mit Schadstoffen: Asbest, Altöl, Farben fachgerecht entsorgen 2027",
    metaTitle: "Schadstoff-Entrümpelung | Asbest, Öl, Farben 2027",
    metaDescription:
      "Entrümpelung mit Schadstoffen: Asbest, Altöl, Farben, Mineralwolle fachgerecht entsorgen. Mit Entsorgungsnachweis. Festpreis im Havelland. ☎ 01579 2639408",
    excerpt:
      "Asbest, Altöl, Farben und Mineralwolle sind Sondermüll – und brauchen Spezialwissen. Wir zeigen, was bei einer Schadstoff-Entrümpelung im Havelland zu beachten ist und was es kostet.",
    publishedAt: "2027-02-24",
    updatedAt: "2027-02-15",
    readingTimeMin: 7,
    category: "Spezial-Räumungen",
    keywords: [
      "entrümpelung schadstoffe",
      "asbest entsorgung",
      "altöl entsorgen entrümpelung",
      "sondermüll entrümpelung",
    ],
    content: [
      { type: "p", text: "Bei alten Häusern und Gewerbeobjekten tauchen Schadstoffe oft erst während der Räumung auf: Asbestplatten im Dach, Heizöl im Tank, alte Farbeimer im Keller, Mineralwolle in der Dämmung. Wer das falsch entsorgt, riskiert hohe Bußgelder und Gesundheitsgefahren. Wir zeigen, wie eine Schadstoff-Entrümpelung im Havelland richtig abläuft." },
      { type: "h2", text: "Welche Schadstoffe sind häufig?" },
      { type: "ul", items: [
        "Asbest: Dachplatten, Bodenbeläge, Fensterbänke (vor 1993 verbaut)",
        "Künstliche Mineralfasern (alte Glas-/Steinwolle) vor 1996",
        "Heizöl, Altöl, Schmierstoffe",
        "Farben, Lacke, Lösemittel, Beizen",
        "PCB in alten Dichtungen und Kondensatoren",
        "Quecksilber in alten Thermometern und Leuchtmitteln",
      ] },
      { type: "h2", text: "Was kostet eine Schadstoff-Entrümpelung 2027?" },
      { type: "p", text: "Schadstoff-Entsorgung wird nach Aufwand und Menge berechnet. Richtwerte für 2027 im Havelland:" },
      { type: "ul", items: [
        "Altöl, Farben, Lacke: 4 – 8 € pro Liter",
        "Asbest (Eternit-Platten): 15 – 30 € pro m²",
        "Mineralwolle (KMF): 8 – 18 € pro m³",
        "Heizöltank-Demontage inkl. Restöl: ab 690 €",
        "Schadstoff-Gutachten (bei Bedarf): ab 290 €",
      ] },
      { type: "h2", text: "Ablauf einer Schadstoff-Räumung" },
      { type: "ol", items: [
        "Besichtigung mit Schadstoff-Sichtung – kostenlos.",
        "Probeentnahme bei Verdacht (Asbest, KMF) – Laborkosten transparent.",
        "Festpreisangebot inkl. Sondermüll und Entsorgungsnachweis.",
        "Räumung in Schutzausrüstung nach TRGS 519 (Asbest) / TRGS 521 (KMF).",
        "Übergabe inkl. amtlichem Entsorgungsnachweis.",
      ] },
      { type: "h2", text: "Wichtig: Niemals selbst Asbest abreißen!" },
      { type: "p", text: "Asbestfasern sind krebserregend. Wer Asbestzement-Platten selbst abreißt oder zerbricht, gefährdet sich, die Nachbarn und macht sich strafbar (BGV A1, TRGS 519). Nur zertifizierte Fachbetriebe dürfen mit Asbest arbeiten." },
      { type: "quote", text: "Wir machen jedes Jahr Räumungen, bei denen Kunden vorher dachten, sie könnten es 'eben schnell selbst'. Bei Asbest ist das nicht nur teuer, sondern lebensgefährlich." },
      { type: "links", title: "Verwandte Ratgeber", items: [
        { label: "Was kostet eine Entrümpelung?", to: "/blog/was-kostet-eine-entruempelung-preise-2026" },
        { label: "Gewerbeentrümpelung", to: "/firmen-gewerbeentruempelung" },
        { label: "Hausentrümpelung", to: "/hausentruempelung" },
      ] },
      { type: "h2", text: "Häufige Fragen" },
      { type: "h3", text: "Bekomme ich einen Entsorgungsnachweis?" },
      { type: "p", text: "Ja – bei jedem Schadstoff erhalten Sie auf Wunsch den amtlichen Entsorgungsnachweis (eANV-konform)." },
      { type: "h3", text: "Muss ich das Bauamt informieren?" },
      { type: "p", text: "Bei Asbest-Sanierungen ist eine Anzeige bei der zuständigen Behörde Pflicht (TRGS 519, ASI-Arbeiten) – wir übernehmen das für Sie." },
      { type: "h3", text: "Wie schnell können Sie kommen?" },
      { type: "p", text: "Besichtigung binnen 24–48 Stunden. Schadstoff-Räumung in der Regel binnen 2 Wochen, je nach Gutachten-Bedarf." },
      { type: "h2", text: "Festpreis für Schadstoff-Räumung anfragen" },
      { type: "p", text: "Rufen Sie an unter 01579 2639408 oder schreiben Sie per WhatsApp – wir beraten Sie zu Asbest, Öl, Farben und allen Sonderfällen." },
    ],
  },
  {
    slug: "dachboden-entruempelung-fruehjahr",
    title: "Frühjahrsputz XXL: Dachboden komplett entrümpeln 2027",
    metaTitle: "Dachboden entrümpeln Frühjahr 2027 | Ablauf & Preise",
    metaDescription:
      "Dachboden im Frühjahr komplett entrümpeln: Preise, Ablauf, Wertanrechnung für Antiquitäten. Festpreis ab 399 € im Havelland. ☎ 01579 2639408",
    excerpt:
      "Der Dachboden ist die letzte Festung des Hausrats – und oft die beste Quelle für Wertanrechnung. Wir zeigen, wie eine komplette Dachboden-Räumung im Frühjahr 2027 abläuft.",
    publishedAt: "2027-03-11",
    updatedAt: "2027-03-15",
    readingTimeMin: 6,
    category: "Saisonale Ratgeber",
    keywords: [
      "dachboden entrümpelung",
      "dachboden räumen frühjahr",
      "spitzboden auflösen",
      "dachboden ausmisten kosten",
    ],
    content: [
      { type: "p", text: "Im Frühjahr ist Dachboden-Zeit. Nach dem Winter ist die Luft trocken, die Temperaturen angenehm, und alles, was über Generationen unter dem Dach gelandet ist, kann endlich raus. Eine Profi-Räumung im Havelland kostet ab 399 € – und bringt oft erstaunliche Antiquitätenfunde zutage." },
      { type: "h2", text: "Was findet sich typischerweise auf Dachböden?" },
      { type: "ul", items: [
        "Alte Möbel der Großeltern (oft echte Antiquitäten!)",
        "Kartons mit Büchern, Schallplatten, Fotoalben",
        "Werkzeug, Nähmaschinen, alte Koffer",
        "Spielzeug aus 3 Generationen",
        "Dachdämmung (oft Mineralwolle – Schadstoff!)",
      ] },
      { type: "h2", text: "Preise 2027" },
      { type: "ul", items: [
        "Kleiner Dachboden (bis 15 m³): 399 – 690 €",
        "Mittlerer Dachboden (15–30 m³): 690 – 1.290 €",
        "Großer Spitzboden mit Antiquitäten: 1.290 – 1.890 €",
        "Mit Wertanrechnung: bis −500 € Erlös",
      ] },
      { type: "h2", text: "Besonderheiten beim Dachboden" },
      { type: "ul", items: [
        "Enge Bodentreppen oder Luken – Möbel müssen oft zerlegt werden",
        "Statik beachten: Manche Böden tragen nicht alles",
        "Hitze und Staub – Schutzausrüstung Pflicht",
        "Alte Dämmung könnte Mineralwolle sein (Sondermüll)",
        "Antiquitäten und Erbstücke immer vorher sichten",
      ] },
      { type: "h2", text: "Ablauf einer Dachboden-Räumung" },
      { type: "ol", items: [
        "Kostenlose Besichtigung mit Antiquitäten-Sichtung.",
        "Schriftliches Festpreisangebot inkl. Wertanrechnung.",
        "Räumung mit kleiner Logistik: 2 Mann, Sackkarren, Treppenseile.",
        "Antike Möbel separat verpackt zur Begutachtung.",
        "Besenreine Übergabe inkl. Bodentreppe.",
      ] },
      { type: "quote", text: "Auf einem Brieselanger Dachboden haben wir mal einen Biedermeier-Sekretär gefunden, der die komplette Räumung bezahlt hat. Es lohnt sich, vor der Entsorgung zu schätzen." },
      { type: "links", title: "Verwandte Ratgeber", items: [
        { label: "Dachbodenentrümpelung", to: "/dachbodenentruempelung" },
        { label: "Wertanrechnung", to: "/blog/entruempelung-mit-wertanrechnung" },
        { label: "Schadstoff-Entrümpelung", to: "/blog/entruempelung-mit-schadstoffen-asbest-oel" },
      ] },
      { type: "h2", text: "Häufige Fragen" },
      { type: "h3", text: "Tragen Sie die Möbel auch über enge Treppen?" },
      { type: "p", text: "Ja. Bei zu engen Treppen demontieren wir oder nutzen Seilzüge über das Fenster." },
      { type: "h3", text: "Erkennen Sie wertvolle Antiquitäten?" },
      { type: "p", text: "Bei wertvollen Stücken holen wir auf Wunsch einen Sachverständigen dazu. Die Anrechnung ist immer transparent." },
      { type: "h3", text: "Was passiert mit alten Fotos und Briefen?" },
      { type: "p", text: "Persönliche Dokumente werden separat verpackt und übergeben – nichts wird ungefragt entsorgt." },
      { type: "h2", text: "Frühjahrs-Termin sichern" },
      { type: "p", text: "Rufen Sie an unter 01579 2639408 oder schreiben Sie per WhatsApp. Im März/April sind die Termine schnell ausgebucht – jetzt vormerken!" },
    ],
  },
  {
    slug: "moebel-entsorgen-spenden-verkaufen",
    title: "Möbel entsorgen, spenden oder verkaufen? Was bringt 2027 wirklich Geld?",
    metaTitle: "Möbel entsorgen oder spenden? | Ratgeber 2027",
    metaDescription:
      "Möbel entsorgen, spenden oder verkaufen? Was bringt Geld, was lohnt nicht. Klarer Ratgeber 2027 mit Spendentipps für das Havelland. ☎ 01579 2639408",
    excerpt:
      "Vor jeder Entrümpelung kommt die Frage: Was kann noch jemand brauchen? Wir zeigen, welche Möbel sich verkaufen lassen, wo Sie im Havelland sinnvoll spenden können und was direkt entsorgt werden sollte.",
    publishedAt: "2027-04-20",
    updatedAt: "2027-04-15",
    readingTimeMin: 6,
    category: "Ratgeber & Vergleich",
    keywords: [
      "möbel entsorgen oder spenden",
      "möbelspende havelland",
      "alte möbel verkaufen",
      "möbel loswerden kostenlos",
    ],
    content: [
      { type: "p", text: "Vor jeder Entrümpelung steht die gleiche Frage: Was kann noch jemand brauchen? Was bringt Geld? Was muss in den Container? Dieser Ratgeber zeigt, was sich 2027 wirklich verkauft, wo Sie im Havelland sinnvoll spenden – und was direkt entsorgt werden sollte." },
      { type: "h2", text: "Was lässt sich noch verkaufen?" },
      { type: "ul", items: [
        "Massivholz-Möbel (Eiche, Buche, Kirsche) – nicht aus Spanplatte",
        "Designer-Klassiker (Vitra, Thonet, USM Haller, IKEA-Kult-Stücke wie Poäng)",
        "Antiquitäten vor 1930 (Sekretäre, Truhen, Spiegel)",
        "Kupfer, Messing, Edelstahl, Bronze",
        "Funktionstüchtige Elektrogeräte unter 5 Jahren (A+++)",
      ] },
      { type: "h2", text: "Wo Sie im Havelland spenden können" },
      { type: "ul", items: [
        "Sozialkaufhaus 'Werder Werke' – Möbel und Hausrat",
        "Caritas Havelland – Möbel für Bedürftige",
        "DRK-Kleiderkammer Falkensee – Kleidung, Bettwäsche",
        "Tafel Brieselang – haltbare Lebensmittel, kleine Hausgeräte",
        "Lokale Flüchtlingshilfe – nach Bedarf",
      ] },
      { type: "p", text: "Wichtig: Spenden müssen sauber, vollständig und gebrauchsfähig sein. Defekte Möbel sind keine Spende, sondern Müll – und werden meist abgelehnt." },
      { type: "h2", text: "Was lässt sich kaum noch verkaufen?" },
      { type: "ul", items: [
        "Eichenschrankwände der 70er und 80er Jahre",
        "Polstermöbel mit Gebrauchsspuren",
        "Großbildfernseher und Röhrenmonitore",
        "Geschirr- und Besteck-Sets in Standardausführung",
        "Bücher (außer Erstausgaben, Fachliteratur)",
      ] },
      { type: "h2", text: "Drei Wege im Vergleich" },
      { type: "ul", items: [
        "Verkauf (eBay Kleinanzeigen): hoher Aufwand, oft kleine Erlöse, viele No-Shows",
        "Spende: schneller, gutes Gefühl, aber nur für gute Ware",
        "Wertanrechnung beim Entrümpler: alles in einem, transparent verrechnet",
      ] },
      { type: "quote", text: "Wer Zeit hat, kann mit Kleinanzeigen 200–500 € rausholen. Wer pragmatisch ist, nimmt unsere Wertanrechnung – das spart Wochen." },
      { type: "links", title: "Verwandte Ratgeber", items: [
        { label: "Wertanrechnung nutzen", to: "/blog/entruempelung-mit-wertanrechnung" },
        { label: "Sperrmüll oder Entrümpelung?", to: "/blog/sperrmuell-oder-entruempelung-vergleich" },
        { label: "Haushaltsauflösung", to: "/haushaltsaufloesung" },
      ] },
      { type: "h2", text: "Häufige Fragen" },
      { type: "h3", text: "Holen Sozialkaufhäuser die Möbel ab?" },
      { type: "p", text: "Manche, aber meist erst nach Sichtung per Foto. Auf Wunsch koordinieren wir die Spenden-Abholung im Rahmen unserer Räumung mit." },
      { type: "h3", text: "Kann ich Spenden steuerlich absetzen?" },
      { type: "p", text: "Sachspenden an gemeinnützige Organisationen sind absetzbar – Sie brauchen aber eine Spendenquittung mit Zeitwert." },
      { type: "h3", text: "Was passiert mit Spielzeug und Kinderbetten?" },
      { type: "p", text: "Gut erhaltenes Spielzeug nimmt die Caritas oder die Flüchtlingshilfe gerne. Babybetten und Hochstühle sind besonders gefragt." },
      { type: "h2", text: "Räumung mit Wertanrechnung kombinieren" },
      { type: "p", text: "Rufen Sie an unter 01579 2639408 oder schreiben Sie per WhatsApp – wir prüfen vor Ort, was verkauft, gespendet oder entsorgt wird." },
    ],
  },
  {
    slug: "entruempelung-fuer-vermieter-mietnomaden",
    title: "Entrümpelung für Vermieter: Mietnomaden, Räumungsklage & Kosten 2027",
    metaTitle: "Entrümpelung Vermieter | Mietnomaden Räumung 2027",
    metaDescription:
      "Vermieter: Wohnung nach Mietnomaden oder Räumungsklage entrümpeln. Kosten, Fristen, Rückforderung. Festpreis im Havelland. ☎ 01579 2639408",
    excerpt:
      "Vermieter stehen oft vor verwüsteten Wohnungen – nach Mietnomaden, nach Räumungsklage, nach Auszug ohne besenreine Übergabe. Wir zeigen Kosten, Fristen und wie Sie das Geld vom Mieter zurückholen.",
    publishedAt: "2027-05-05",
    updatedAt: "2027-05-15",
    readingTimeMin: 7,
    category: "Vermieter & Gewerbe",
    keywords: [
      "entrümpelung vermieter",
      "mietnomaden räumung",
      "wohnung nach räumungsklage entrümpeln",
      "vermieter mieter wohnung räumen",
    ],
    content: [
      { type: "p", text: "Für Vermieter im Havelland ist eine verwüstete Wohnung nach Mietnomaden oder Räumungsklage ein Albtraum. Jeder Tag Leerstand kostet Miete, jede verlorene Woche verzögert die Neuvermietung. Wir zeigen, wie eine professionelle Räumung in solchen Fällen abläuft – und wie Sie Ihr Geld vom Mieter zurückbekommen." },
      { type: "h2", text: "Typische Vermieter-Situationen" },
      { type: "ul", items: [
        "Mietnomade hinterlässt vollgestopfte Wohnung",
        "Räumungsurteil ergangen – Räumung durch Gerichtsvollzieher",
        "Mieter ausgezogen, aber nichts mitgenommen",
        "Todesfall, keine Erben oder Erben unbekannt",
        "Geistige Verwirrung des Mieters, Wohnung vermüllt",
      ] },
      { type: "h2", text: "Kosten 2027 für Vermieter-Räumungen" },
      { type: "ul", items: [
        "1-Zimmer-Wohnung (Standard-Verwüstung): 990 – 1.690 €",
        "2-3-Zimmer-Wohnung: 1.690 – 2.890 €",
        "Messie-Level mit Schädlingen: +30–60 % Aufschlag",
        "Schadstoff-Anteil (Schimmel, Fäkalien): nach Aufwand",
        "Schlossaustausch direkt vor Ort: ab 90 €",
      ] },
      { type: "h2", text: "Berliner Räumung vs. komplette Entrümpelung" },
      { type: "p", text: "Bei der 'Berliner Räumung' wird nur das Schloss ausgetauscht und der Hausrat eingelagert (gesetzliche Aufbewahrungsfrist 1 Monat). Bei einer kompletten Entrümpelung räumen wir alles auf einmal raus. Welche Variante besser ist, hängt vom Räumungsurteil ab – wir beraten Sie." },
      { type: "h2", text: "So holen Sie Ihr Geld zurück" },
      { type: "ol", items: [
        "Vor Räumung: detaillierte Foto-Dokumentation (Beweissicherung).",
        "Räumungskosten werden vom Mieter geschuldet (§ 280 BGB i.V.m. Mietvertrag).",
        "Rechnung dem Mieter zustellen mit Fristsetzung.",
        "Bei Nichtzahlung: Mahnbescheid über das zuständige Amtsgericht.",
        "Vollstreckung über Gerichtsvollzieher – realistisch oft nur bei zahlungsfähigen Mietern.",
      ] },
      { type: "p", text: "Wichtig: Die Kosten sind als Werbungskosten in der Steuererklärung absetzbar – auch wenn Sie das Geld nie vom Mieter zurückbekommen." },
      { type: "quote", text: "Wir arbeiten regelmäßig für Vermieter und Hausverwaltungen im Havelland. Foto-Dokumentation, schnelle Räumung, Schlossaustausch – alles aus einer Hand." },
      { type: "links", title: "Verwandte Ratgeber", items: [
        { label: "Wer trägt die Kosten?", to: "/blog/wer-traegt-kosten-entruempelung" },
        { label: "Entrümpelung steuerlich absetzen", to: "/blog/entruempelung-steuerlich-absetzen" },
        { label: "Messie-Wohnung räumen", to: "/blog/messie-wohnung-entruempeln-diskret" },
      ] },
      { type: "h2", text: "Häufige Fragen" },
      { type: "h3", text: "Brauche ich ein Räumungsurteil?" },
      { type: "p", text: "Bei bestehendem Mietverhältnis ja – Selbstjustiz ist strafbar. Bei beendetem Mietverhältnis und freiwillig zurückgelassenem Hausrat reicht eine Aufforderung mit Frist." },
      { type: "h3", text: "Kommen Sie auch zum Gerichtsvollzieher-Termin?" },
      { type: "p", text: "Ja – wir sind regelmäßig bei Räumungsterminen mit dem Gerichtsvollzieher dabei. Sie buchen, wir koordinieren." },
      { type: "h3", text: "Wie schnell kann neu vermietet werden?" },
      { type: "p", text: "Nach kompletter Räumung inkl. Reinigung in der Regel binnen 5–10 Werktagen – wir koordinieren auf Wunsch direkt mit Hausverwaltung und Malerbetrieb." },
      { type: "h2", text: "Vermieter-Hotline" },
      { type: "p", text: "Rufen Sie an unter 01579 2639408 oder schreiben Sie per WhatsApp. Wir kennen das Thema, arbeiten schnell und stellen Rechnungen, die der Mieter direkt anerkennen muss." },
    ],
  },
];

// ============================================================
// PUBLISH-FILTER (automatischer monatlicher Release)
// ============================================================
// Artikel mit publishedAt in der Zukunft erscheinen automatisch am angegebenen Datum.

const isPublished = (post: BlogPost): boolean => {
  const today = new Date();
  today.setHours(23, 59, 59, 999);
  return new Date(post.publishedAt) <= today;
};

/** Alle bereits veröffentlichten Posts, sortiert nach Datum (neueste zuerst). */
export const getPublishedPosts = (): BlogPost[] =>
  BLOG_POSTS.filter(isPublished).sort(
    (a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime()
  );

export const getBlogPostBySlug = (slug: string): BlogPost | undefined => {
  const post = BLOG_POSTS.find((p) => p.slug === slug);
  if (!post) return undefined;
  // Zukunfts-Artikel sind noch nicht direkt aufrufbar
  return isPublished(post) ? post : undefined;
};

export const getRelatedPosts = (currentSlug: string, limit = 3): BlogPost[] =>
  getPublishedPosts()
    .filter((p) => p.slug !== currentSlug)
    .slice(0, limit);
